services:
  kafka-local:
    image: bitnami/kafka:latest
    ports:
    - 9092:9092
    container_name: kafka-local
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ADDRESS}:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${IP_MACHINE}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 4
      ALLOW_PLAINTEXT_LISTENER: yes

